// <auto-generated />
using System;
using IRentNG.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IRentNG.Repository.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230915151136_DataSeeder")]
    partial class DataSeeder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IRentNG.Entities.Models.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PropertyId");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<string>("CoverPhotoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<int>("Privacy")
                        .HasColumnType("int");

                    b.Property<string>("PropertyAmenities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyPhotosURLs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Structure")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("84ebbb16-57bc-4dbf-8f91-391f48113ca2"),
                            Address = "1 Victoria Island, Lagos",
                            Bathrooms = 2,
                            Bedrooms = 3,
                            CoverPhotoURL = "https://example.com/property1-cover.jpg",
                            CreatedDate = new DateTime(2023, 9, 15, 16, 11, 35, 927, DateTimeKind.Local).AddTicks(8554),
                            Description = "Experience luxury living in this spacious apartment located in the heart of Lagos Island. This stunning three-bedroom apartment features a modern kitchen, beautiful city views, and access to top-notch amenities.",
                            Duration = 1,
                            Price = 2500000.00m,
                            Privacy = 1,
                            PropertyAmenities = "Kitchen, Wifi, AirConditioning, FreeParkingOnPremises",
                            PropertyPhotosURLs = "https://example.com/property1-photo1.jpg,https://example.com/property1-photo2.jpg",
                            Structure = 1,
                            Title = "Luxury Apartment in Lagos Island",
                            UserId = "9FE6F8FB-CE97-4DAE-AE02-0B3AC6B114FA"
                        },
                        new
                        {
                            Id = new Guid("1057a090-8277-4351-b135-b119ab61d24e"),
                            Address = "12 Garki, Abuja",
                            Bathrooms = 4,
                            Bedrooms = 5,
                            CoverPhotoURL = "https://example.com/property2-cover.jpg",
                            CreatedDate = new DateTime(2023, 9, 15, 16, 11, 35, 927, DateTimeKind.Local).AddTicks(8570),
                            Description = "Indulge in luxury at this stunning villa in Abuja. This spacious five-bedroom villa features a private pool, lush gardens, and a fully equipped kitchen. Perfect for special events or a relaxing getaway.",
                            Duration = 1,
                            Price = 5000000.00m,
                            Privacy = 1,
                            PropertyAmenities = "Kitchen, Tv, Wifi, AirConditioning, Pool, BBQGrill",
                            PropertyPhotosURLs = "https://example.com/property2-photo1.jpg,https://example.com/property2-photo2.jpg",
                            Structure = 9,
                            Title = "Luxury Villa in Abuja",
                            UserId = "9FE6F8FB-CE97-4DAE-AE02-0B3AC6B114FA"
                        },
                        new
                        {
                            Id = new Guid("5560f929-f2cd-44b5-bd84-4d39abca0595"),
                            Address = "3 Ocean View Drive, Victoria Island",
                            Bathrooms = 2,
                            Bedrooms = 3,
                            CoverPhotoURL = "https://example.com/property3-cover.jpg",
                            CreatedDate = new DateTime(2023, 9, 15, 16, 11, 35, 927, DateTimeKind.Local).AddTicks(8582),
                            Description = "A spacious apartment with 3 bedrooms, 2 bathrooms, and a stunning view of the ocean. Located in the upscale Victoria Island neighborhood, this property offers luxury living, a fully equipped kitchen, and access to a private pool and gym.",
                            Duration = 1,
                            Price = 3500000.00m,
                            Privacy = 1,
                            PropertyAmenities = "Kitchen, Tv, Wifi, AirConditioning, Pool, Gym",
                            PropertyPhotosURLs = "https://example.com/property3-photo1.jpg,https://example.com/property3-photo2.jpg",
                            Structure = 1,
                            Title = "Spacious Apartment in Victoria Island",
                            UserId = "9FE6F8FB-CE97-4DAE-AE02-0B3AC6B114FA"
                        },
                        new
                        {
                            Id = new Guid("2a8c28f3-d0e3-42fe-b87e-359a1bc13e3c"),
                            Address = "4 Lekki Gardens, Lekki",
                            Bathrooms = 3,
                            Bedrooms = 4,
                            CoverPhotoURL = "https://example.com/property4-cover.jpg",
                            CreatedDate = new DateTime(2023, 9, 15, 16, 11, 35, 927, DateTimeKind.Local).AddTicks(8593),
                            Description = "A modern terrace duplex with 4 bedrooms, 3 bathrooms, and contemporary design. This property is situated in the trendy Lekki neighborhood and offers spacious rooms, a sleek kitchen, and a rooftop terrace with stunning views.",
                            Duration = 2,
                            Price = 600000.00m,
                            Privacy = 1,
                            PropertyAmenities = "Kitchen, Tv, Wifi, AirConditioning, RooftopTerrace",
                            PropertyPhotosURLs = "https://example.com/property4-photo1.jpg,https://example.com/property4-photo2.jpg",
                            Structure = 6,
                            Title = "Modern Terrace Duplex in Lekki",
                            UserId = "9FE6F8FB-CE97-4DAE-AE02-0B3AC6B114FA"
                        },
                        new
                        {
                            Id = new Guid("d40e1a94-203f-4f56-8450-531906fe43d0"),
                            Address = "5 Calabar Lane, Calabar",
                            Bathrooms = 6,
                            Bedrooms = 6,
                            CoverPhotoURL = "https://example.com/property5-cover.jpg",
                            CreatedDate = new DateTime(2023, 9, 15, 16, 11, 35, 927, DateTimeKind.Local).AddTicks(8624),
                            Description = "A charming guest house with 6 cozy rooms, each with its own bathroom. This guest house is located in the beautiful city of Calabar and offers a garden, free Wi-Fi, and a dedicated workspace. Perfect for travelers.",
                            Duration = 2,
                            Price = 450000.00m,
                            Privacy = 1,
                            PropertyAmenities = "Kitchen, Tv, Wifi, DedicatedWorkspace, Garden",
                            PropertyPhotosURLs = "https://example.com/property5-photo1.jpg,https://example.com/property5-photo2.jpg",
                            Structure = 3,
                            Title = "Charming Guest House in Calabar",
                            UserId = "826E0C43-871D-4498-B343-8F8260E1127C"
                        },
                        new
                        {
                            Id = new Guid("43dfef41-4c65-4cc3-ba67-aba865cda88f"),
                            Address = "6 Marina Drive, Lagos",
                            Bathrooms = 4,
                            Bedrooms = 5,
                            CoverPhotoURL = "https://example.com/property6-cover.jpg",
                            CreatedDate = new DateTime(2023, 9, 15, 16, 11, 35, 927, DateTimeKind.Local).AddTicks(8653),
                            Description = "Experience luxury living in this spacious penthouse with 5 bedrooms, 4 bathrooms, and breathtaking views of Lagos. This penthouse features a gourmet kitchen, private elevator access, and access to a rooftop pool and lounge.",
                            Duration = 2,
                            Price = 1000000.00m,
                            Privacy = 1,
                            PropertyAmenities = "Kitchen, Tv, Wifi, AirConditioning, RooftopPool",
                            PropertyPhotosURLs = "https://example.com/property6-photo1.jpg,https://example.com/property6-photo2.jpg",
                            Structure = 8,
                            Title = "Luxurious Penthouse in Lagos",
                            UserId = "826E0C43-871D-4498-B343-8F8260E1127C"
                        },
                        new
                        {
                            Id = new Guid("d586440f-afc9-4f09-9624-70cb4c2e5c9d"),
                            Address = "7 Diplomat Avenue, Abuja",
                            Bathrooms = 6,
                            Bedrooms = 7,
                            CoverPhotoURL = "https://example.com/property7-cover.jpg",
                            CreatedDate = new DateTime(2023, 9, 15, 16, 11, 35, 927, DateTimeKind.Local).AddTicks(8665),
                            Description = "Step into this majestic mansion with 7 bedrooms, 6 bathrooms, and exquisite architecture. Located in the diplomatic zone of Abuja, this property offers a grand entrance, lush gardens, and a private cinema room.",
                            Duration = 1,
                            Price = 10000000.00m,
                            Privacy = 1,
                            PropertyAmenities = "Kitchen, Tv, Wifi, AirConditioning, Cinema, Garden",
                            PropertyPhotosURLs = "https://example.com/property7-photo1.jpg,https://example.com/property7-photo2.jpg",
                            Structure = 9,
                            Title = "Majestic Mansion in Abuja",
                            UserId = "826E0C43-871D-4498-B343-8F8260E1127C"
                        },
                        new
                        {
                            Id = new Guid("02088ebe-9ecd-4008-ad77-ee1d292eeb8f"),
                            Address = "8 Riverside Street, Port Harcourt",
                            Bathrooms = 2,
                            Bedrooms = 3,
                            CoverPhotoURL = "https://example.com/property8-cover.jpg",
                            CreatedDate = new DateTime(2023, 9, 15, 16, 11, 35, 927, DateTimeKind.Local).AddTicks(8677),
                            Description = "Discover modern living in this beautiful maisonette with 3 bedrooms, 2 bathrooms, and a contemporary design. Located in Port Harcourt's upscale neighborhood, this property offers a stylish kitchen, a private garden, and easy access to local amenities.",
                            Duration = 1,
                            Price = 2800000.00m,
                            Privacy = 1,
                            PropertyAmenities = "Kitchen, Tv, Wifi, AirConditioning, Garden",
                            PropertyPhotosURLs = "https://example.com/property8-photo1.jpg,https://example.com/property8-photo2.jpg",
                            Structure = 7,
                            Title = "Modern Maisonette in Port Harcourt",
                            UserId = "91F6AFD4-8D50-40B1-B09E-E799723E952D"
                        },
                        new
                        {
                            Id = new Guid("250908e6-99fc-48e9-a335-f43fcbc1fa6e"),
                            Address = "9 Riverside Drive, Port Harcourt",
                            Bathrooms = 5,
                            Bedrooms = 6,
                            CoverPhotoURL = "https://example.com/property9-cover.jpg",
                            CreatedDate = new DateTime(2023, 9, 15, 16, 11, 35, 927, DateTimeKind.Local).AddTicks(8688),
                            Description = "Experience riverside living in this grand mansion with 6 bedrooms, 5 bathrooms, and panoramic views of the river. This mansion boasts a private dock, a spacious dining hall, and beautifully landscaped gardens.",
                            Duration = 1,
                            Price = 7500000.00m,
                            Privacy = 1,
                            PropertyAmenities = "Kitchen, Tv, Wifi, AirConditioning, PrivateDock, Garden",
                            PropertyPhotosURLs = "https://example.com/property9-photo1.jpg,https://example.com/property9-photo2.jpg",
                            Structure = 9,
                            Title = "Riverside Mansion in Port Harcourt",
                            UserId = "91F6AFD4-8D50-40B1-B09E-E799723E952D"
                        },
                        new
                        {
                            Id = new Guid("5fd0c9ec-9c94-43e6-80a4-f3007105e654"),
                            Address = "10 Lekki Gardens, Lekki",
                            Bathrooms = 2,
                            Bedrooms = 3,
                            CoverPhotoURL = "https://example.com/property10-cover.jpg",
                            CreatedDate = new DateTime(2023, 9, 15, 16, 11, 35, 927, DateTimeKind.Local).AddTicks(8711),
                            Description = "Discover elegance in this terrace duplex with 3 bedrooms, 2 bathrooms, and modern design. Located in Lekki's upscale neighborhood, this property offers a well-appointed kitchen, a cozy living room, and a private courtyard.",
                            Duration = 2,
                            Price = 300000.00m,
                            Privacy = 1,
                            PropertyAmenities = "Kitchen, Tv, Wifi, AirConditioning, PrivateCourtyard",
                            PropertyPhotosURLs = "https://example.com/property10-photo1.jpg,https://example.com/property10-photo2.jpg",
                            Structure = 6,
                            Title = "Elegant Terrace Duplex in Lekki",
                            UserId = "3F373D01-67C5-4FBC-92BB-3C84117CAE7B"
                        },
                        new
                        {
                            Id = new Guid("62620db4-6119-4dc6-951a-199c3ebb2681"),
                            Address = "11 Beachfront Lane, Lagos",
                            Bathrooms = 3,
                            Bedrooms = 4,
                            CoverPhotoURL = "https://example.com/property11-cover.jpg",
                            CreatedDate = new DateTime(2023, 9, 15, 16, 11, 35, 927, DateTimeKind.Local).AddTicks(8720),
                            Description = "Escape to this seaside villa with 4 bedrooms, 3 bathrooms, and direct access to the beach. This villa offers a fully equipped kitchen, a private swimming pool, and breathtaking sunset views over the ocean.",
                            Duration = 1,
                            Price = 5500000.00m,
                            Privacy = 1,
                            PropertyAmenities = "Kitchen, Tv, Wifi, AirConditioning, PrivatePool, BeachAccess",
                            PropertyPhotosURLs = "https://example.com/property11-photo1.jpg,https://example.com/property11-photo2.jpg",
                            Structure = 10,
                            Title = "Seaside Villa in Lagos",
                            UserId = "3F373D01-67C5-4FBC-92BB-3C84117CAE7B"
                        },
                        new
                        {
                            Id = new Guid("042a5756-48fd-4d8a-b99c-fd31cf773ff8"),
                            Address = "12 Green Hills Road, Enugu",
                            Bathrooms = 1,
                            Bedrooms = 2,
                            CoverPhotoURL = "https://example.com/property12-cover.jpg",
                            CreatedDate = new DateTime(2023, 9, 15, 16, 11, 35, 927, DateTimeKind.Local).AddTicks(8730),
                            Description = "Experience eco-friendly living in this cozy cottage with 2 bedrooms, 1 bathroom, and sustainable features. Located in the serene hills of Enugu, this cottage offers a vegetable garden, solar & inverter, and a tranquil atmosphere.",
                            Duration = 2,
                            Price = 1800000.00m,
                            Privacy = 1,
                            PropertyAmenities = "Kitchen, Tv, Wifi, SolarAndInverter, VegetableGarden",
                            PropertyPhotosURLs = "https://example.com/property12-photo1.jpg,https://example.com/property12-photo2.jpg",
                            Structure = 11,
                            Title = "Eco-Friendly Cottage in Enugu",
                            UserId = "3F373D01-67C5-4FBC-92BB-3C84117CAE7B"
                        },
                        new
                        {
                            Id = new Guid("b3afbe97-9551-487e-991f-13040a95e020"),
                            Address = "13 Heritage Street, Abeokuta",
                            Bathrooms = 4,
                            Bedrooms = 6,
                            CoverPhotoURL = "https://example.com/property13-cover.jpg",
                            CreatedDate = new DateTime(2023, 9, 15, 16, 11, 35, 927, DateTimeKind.Local).AddTicks(8739),
                            Description = "Step into history in this historic villa with 6 bedrooms, 4 bathrooms, and antique charm. Located in the heart of Abeokuta, this villa features original architecture, a library, and a spacious courtyard.",
                            Duration = 2,
                            Price = 420000.00m,
                            Privacy = 1,
                            PropertyAmenities = "Kitchen, Tv, Wifi, Library, Courtyard",
                            PropertyPhotosURLs = "https://example.com/property13-photo1.jpg,https://example.com/property13-photo2.jpg",
                            Structure = 10,
                            Title = "Historic Villa in Abeokuta",
                            UserId = "0C2E622E-49D1-4A80-AB68-A5AB3A213877"
                        },
                        new
                        {
                            Id = new Guid("50f9a624-c6b0-4379-878a-e33cdb54a59c"),
                            Address = "14 Forest Retreat, Ondo",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            CoverPhotoURL = "https://example.com/property14-cover.jpg",
                            CreatedDate = new DateTime(2023, 9, 15, 16, 11, 35, 927, DateTimeKind.Local).AddTicks(8756),
                            Description = "Escape to nature in this secluded cabin with 1 bedroom, 1 bathroom, and a tranquil forest setting. Located deep in the Ondo Forest, this cabin offers a fireplace, hiking trails, and a true getaway from the city.",
                            Duration = 2,
                            Price = 120000.00m,
                            Privacy = 1,
                            PropertyAmenities = "Kitchen, Fireplace, HikingTrails",
                            PropertyPhotosURLs = "https://example.com/property14-photo1.jpg,https://example.com/property14-photo2.jpg",
                            Structure = 12,
                            Title = "Secluded Cabin in Ondo Forest",
                            UserId = "0C2E622E-49D1-4A80-AB68-A5AB3A213877"
                        },
                        new
                        {
                            Id = new Guid("f0837def-f322-47ed-97e3-6a73ce806607"),
                            Address = "15 Oceanview Road, Lagos",
                            Bathrooms = 3,
                            Bedrooms = 4,
                            CoverPhotoURL = "https://example.com/property15-cover.jpg",
                            CreatedDate = new DateTime(2023, 9, 15, 16, 11, 35, 927, DateTimeKind.Local).AddTicks(8768),
                            Description = "Indulge in luxury at this beachfront villa with 4 bedrooms, 3 bathrooms, and direct access to the ocean. This villa offers a private chef, infinity pool, and stunning sunset views over the Atlantic.",
                            Duration = 3,
                            Price = 100000.00m,
                            Privacy = 1,
                            PropertyAmenities = "Kitchen, Tv, Wifi, AirConditioning, Pool, PrivateChef",
                            PropertyPhotosURLs = "https://example.com/property15-photo1.jpg,https://example.com/property15-photo2.jpg",
                            Structure = 10,
                            Title = "Luxury Beachfront Villa in Lagos",
                            UserId = "0C2E622E-49D1-4A80-AB68-A5AB3A213877"
                        },
                        new
                        {
                            Id = new Guid("747b4f4b-f91e-444c-ac8f-e5ccc9ff7ff4"),
                            Address = "16 Marina View, Lagos",
                            Bathrooms = 2,
                            Bedrooms = 2,
                            CoverPhotoURL = "https://example.com/property16-cover.jpg",
                            CreatedDate = new DateTime(2023, 9, 15, 16, 11, 35, 927, DateTimeKind.Local).AddTicks(8780),
                            Description = "Enjoy modern living in this waterfront apartment with 2 bedrooms, 2 bathrooms, and stunning views of Lagos Island. This apartment features a fully equipped kitchen, fitness center, and 24/7 concierge service.",
                            Duration = 3,
                            Price = 45000.00m,
                            Privacy = 1,
                            PropertyAmenities = "Kitchen, Tv, Wifi, AirConditioning, FitnessCenter, Concierge",
                            PropertyPhotosURLs = "https://example.com/property16-photo1.jpg,https://example.com/property16-photo2.jpg",
                            Structure = 1,
                            Title = "Modern Waterfront Apartment in Lagos Island",
                            UserId = "0C2E622E-49D1-4A80-AB68-A5AB3A213877"
                        },
                        new
                        {
                            Id = new Guid("429a1dc2-5f02-4a02-bc0a-57fcc16b433a"),
                            Address = "17 Skyline Towers, Lagos",
                            Bathrooms = 2,
                            Bedrooms = 3,
                            CoverPhotoURL = "https://example.com/property17-cover.jpg",
                            CreatedDate = new DateTime(2023, 9, 15, 16, 11, 35, 927, DateTimeKind.Local).AddTicks(8789),
                            Description = "Live in luxury at this Lagos penthouse with 3 bedrooms, 2 bathrooms, and panoramic skyline views. This penthouse offers a rooftop terrace, spa, and private elevator access.",
                            Duration = 1,
                            Price = 5500000.00m,
                            Privacy = 1,
                            PropertyAmenities = "Kitchen, Tv, Wifi, AirConditioning, RooftopTerrace, Spa",
                            PropertyPhotosURLs = "https://example.com/property17-photo1.jpg,https://example.com/property17-photo2.jpg",
                            Structure = 8,
                            Title = "Luxurious Lagos Penthouse with Skyline Views",
                            UserId = "0C2E622E-49D1-4A80-AB68-A5AB3A213877"
                        },
                        new
                        {
                            Id = new Guid("07b80f7d-0b4e-4067-88c9-cb3e9cf5d2f0"),
                            Address = "18 Cityscape Lane, Lagos",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            CoverPhotoURL = "https://example.com/property18-cover.jpg",
                            CreatedDate = new DateTime(2023, 9, 15, 16, 11, 35, 927, DateTimeKind.Local).AddTicks(8800),
                            Description = "Experience urban living in this contemporary loft with 1 bedroom, 1 bathroom, and breathtaking city views. This loft offers an open-concept design, modern furnishings, and easy access to Lagos nightlife.",
                            Duration = 2,
                            Price = 100000.00m,
                            Privacy = 2,
                            PropertyAmenities = "Kitchen, Tv, Wifi, AirConditioning",
                            PropertyPhotosURLs = "https://example.com/property18-photo1.jpg,https://example.com/property18-photo2.jpg",
                            Structure = 1,
                            Title = "Contemporary Lagos Loft with City Views",
                            UserId = "0C2E622E-49D1-4A80-AB68-A5AB3A213877"
                        },
                        new
                        {
                            Id = new Guid("11de0802-2b14-4e24-8e9c-4f0cc0f56d06"),
                            Address = "19 Lagoonview Drive, Lagos",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            CoverPhotoURL = "https://example.com/property19-cover.jpg",
                            CreatedDate = new DateTime(2023, 9, 15, 16, 11, 35, 927, DateTimeKind.Local).AddTicks(8809),
                            Description = "Escape to this serene waterfront retreat with 1 bedroom, 1 bathroom, and direct access to the lagoon. This retreat features a private boat dock, lush gardens, and a peaceful atmosphere.",
                            Duration = 2,
                            Price = 200000.00m,
                            Privacy = 2,
                            PropertyAmenities = "Kitchen, Tv, Wifi, LagoonAccess, BoatDock, Gardens",
                            PropertyPhotosURLs = "https://example.com/property19-photo1.jpg,https://example.com/property19-photo2.jpg",
                            Structure = 3,
                            Title = "Serene Waterfront Retreat in Lagos",
                            UserId = "0C2E622E-49D1-4A80-AB68-A5AB3A213877"
                        },
                        new
                        {
                            Id = new Guid("22670d16-8f81-4faa-be44-319c391b8dd9"),
                            Address = "20 Luxury Avenue, Victoria Island, Lagos",
                            Bathrooms = 2,
                            Bedrooms = 2,
                            CoverPhotoURL = "https://example.com/property20-cover.jpg",
                            CreatedDate = new DateTime(2023, 9, 15, 16, 11, 35, 927, DateTimeKind.Local).AddTicks(8818),
                            Description = "Live in style at this modern apartment with 2 bedrooms, 2 bathrooms, and city views in Victoria Island. This apartment offers sleek design, a fitness center, and proximity to top restaurants.",
                            Duration = 2,
                            Price = 450000.00m,
                            Privacy = 1,
                            PropertyAmenities = "Kitchen, Tv, Wifi, AirConditioning, FitnessCenter, DiningOptions",
                            PropertyPhotosURLs = "https://example.com/property20-photo1.jpg,https://example.com/property20-photo2.jpg",
                            Structure = 1,
                            Title = "Modern Apartment in Victoria Island",
                            UserId = "0C2E622E-49D1-4A80-AB68-A5AB3A213877"
                        });
                });

            modelBuilder.Entity("IRentNG.Entities.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermanentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "579CB2F2-5256-4014-8279-08F527B7F302",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "461c2ea2-3c96-4584-9e4d-f569f38f6d22",
                            DateJoined = new DateTime(2023, 9, 15, 16, 11, 34, 813, DateTimeKind.Local).AddTicks(1278),
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            FullName = "Josh Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENPas5qEABfP9E6h8WcTA8vj1byEMENlzDyKBN+GVcpqi6jbQM7owZPUERFvUMljDg==",
                            PermanentAddress = "123 Main Street",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "https://example.com/user1.jpg",
                            SecurityStamp = "998c7b63-f5f1-4719-9922-33591349e080",
                            TwoFactorEnabled = false,
                            UserName = "admin@example.com"
                        },
                        new
                        {
                            Id = "6A5C9A15-7F19-46FF-9E1D-62D617126006",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dc4c5044-46d8-496a-b997-4e4f4de5c7f3",
                            DateJoined = new DateTime(2023, 9, 15, 16, 11, 35, 29, DateTimeKind.Local).AddTicks(5274),
                            Email = "landlord@example.com",
                            EmailConfirmed = true,
                            FullName = "Josh Landlord",
                            LockoutEnabled = false,
                            NormalizedEmail = "LANDLORD@EXAMPLE.COM",
                            NormalizedUserName = "LANDLORD@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENy+rN7CXNcB3kTNvQfjQz6CLTiHyyw2QmrJNvh7kcsU1sfF7cjm+UPZl6q/3dGAQw==",
                            PermanentAddress = "456 Elm Street",
                            PhoneNumber = "+2349025621988",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "https://example.com/user2.jpg",
                            SecurityStamp = "56aeedf1-5a3c-49bf-9b67-ca41193f63bd",
                            TwoFactorEnabled = false,
                            UserName = "landlord@example.com"
                        },
                        new
                        {
                            Id = "9FE6F8FB-CE97-4DAE-AE02-0B3AC6B114FA",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a3f376ad-33b4-4a11-b218-8e9e7c6c2f3c",
                            DateJoined = new DateTime(2023, 9, 15, 16, 11, 35, 224, DateTimeKind.Local).AddTicks(9044),
                            Email = "landlord1@example.com",
                            EmailConfirmed = false,
                            FullName = "John Landlord",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEF1he9+OqmdIfH4Sdf3B5HckO8Wii7rrQ1kf7OCS+63L1vWCuoS2C7Onr7qYMwnXGw==",
                            PermanentAddress = "123 Landlord Lane, Lagos",
                            PhoneNumber = "+1234567890",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "https://example.com/profile1.jpg",
                            SecurityStamp = "d89e6ca3-0f8d-4986-88b8-0055fa523ff6",
                            TwoFactorEnabled = false,
                            UserName = "landlord1@example.com"
                        },
                        new
                        {
                            Id = "826E0C43-871D-4498-B343-8F8260E1127C",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3e311e15-8454-4eb2-8166-fec42c9f6d0c",
                            DateJoined = new DateTime(2023, 9, 15, 16, 11, 35, 414, DateTimeKind.Local).AddTicks(4446),
                            Email = "landlord2@example.com",
                            EmailConfirmed = false,
                            FullName = "Jane PropertyOwner",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEMHafzqe6Wrt4puAyCbfthPhSw3IAKRVk6MvovrerbvKvq+skq0q4uNOGofjhdjOEg==",
                            PermanentAddress = "456 Landlord Street, Abuja",
                            PhoneNumber = "+2345678901",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "https://example.com/profile2.jpg",
                            SecurityStamp = "d52808e8-8ff3-4694-893f-61a9d07b038a",
                            TwoFactorEnabled = false,
                            UserName = "landlord2@example.com"
                        },
                        new
                        {
                            Id = "91F6AFD4-8D50-40B1-B09E-E799723E952D",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1662c153-ccff-483f-976c-49e9688f60ad",
                            DateJoined = new DateTime(2023, 9, 15, 16, 11, 35, 603, DateTimeKind.Local).AddTicks(9509),
                            Email = "landlord3@example.com",
                            EmailConfirmed = false,
                            FullName = "Chris RealEstate",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEIBb3bbgiee1+ktmocLpmBcG4GepN97XlSvclFwEKQm340qcP5cNuTS96yqwyV/uKw==",
                            PermanentAddress = "789 Rental Road, Lagos",
                            PhoneNumber = "+3456789012",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "https://example.com/profile3.jpg",
                            SecurityStamp = "e248bd7c-3eed-437a-bb3d-76fe076ba166",
                            TwoFactorEnabled = false,
                            UserName = "landlord3@example.com"
                        },
                        new
                        {
                            Id = "3F373D01-67C5-4FBC-92BB-3C84117CAE7B",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4f320083-8adc-4ac3-a896-231016d38569",
                            DateJoined = new DateTime(2023, 9, 15, 16, 11, 35, 786, DateTimeKind.Local).AddTicks(44),
                            Email = "landlord4@example.com",
                            EmailConfirmed = false,
                            FullName = "Laura Landlord",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAELGOaq6cV+AJUL3FH+jrPp7I0IxEqZYRmh5RjF5HNarYp1Wj02asocAVAYkWkEvxMg==",
                            PermanentAddress = "101 Landlord Avenue, Abuja",
                            PhoneNumber = "+4567890123",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "https://example.com/profile4.jpg",
                            SecurityStamp = "1c6df5fa-e0be-4430-9ad3-0f0a68315473",
                            TwoFactorEnabled = false,
                            UserName = "landlord4@example.com"
                        },
                        new
                        {
                            Id = "0C2E622E-49D1-4A80-AB68-A5AB3A213877",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "160001d6-ba8e-4bb4-9702-0b4aa6df5946",
                            DateJoined = new DateTime(2023, 9, 15, 16, 11, 35, 927, DateTimeKind.Local).AddTicks(6140),
                            Email = "landlord5@example.com",
                            EmailConfirmed = false,
                            FullName = "David Rental",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEGuHk0eTtYm0MM74vYEQaddwELLXEKB93pKzf84v9bgvyP/Pt9aIh8ttk35+F+TBIw==",
                            PermanentAddress = "234 Property Place, Lagos",
                            PhoneNumber = "+5678901234",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "https://example.com/profile5.jpg",
                            SecurityStamp = "6d09f82a-3944-409a-8db5-040f12015e95",
                            TwoFactorEnabled = false,
                            UserName = "landlord5@example.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0c565282-7fac-4429-8cfe-0268259bb6c0",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "00ab5334-1317-4aa1-9c9c-59d834f812da",
                            Name = "Landlord",
                            NormalizedName = "LANDLORD"
                        },
                        new
                        {
                            Id = "d0aeabaf-ebaf-4208-9fff-6e2d1c2f04f8",
                            Name = "Tenant",
                            NormalizedName = "TENANT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("IRentNG.Entities.Models.Property", b =>
                {
                    b.HasOne("IRentNG.Entities.Models.User", "User")
                        .WithMany("Properties")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("IRentNG.Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("IRentNG.Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRentNG.Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("IRentNG.Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IRentNG.Entities.Models.User", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
